### PR TITLE
delete-survey

### PR DESCRIPTION
**Pull request by Rayatk**
Changed the POST endpoints to DELETE and added a js file too. Tried using the previous hidden method but opted to use AJAX as this was being recommended everywhere. Check as I'm not sure if it works.

### CODE REVIEW

**Comment by Rayatk** [comment]
> Tests are failing, please fix. The specific test that failed can be seen here: https://github.com/Andrei486/sysc-4806-project/actions/runs/7130186670/job/19416138143?pr=74#step:4:3112

passes now

**Review by Andrei486 — COMMENTED** [review]
Looks pretty good. The one thing to change is to have your "delete survey" button replace the old button - currently there are two buttons. Once that's done I'll approve. Good work!

**Comment by Rayatk** [comment]
There were two view results buttons too but I've changed them. The request mapping is because it should be handling both post and delete because of html method. But does it actually work?

**Comment by Andrei486** [comment]
I haven't tested the POST request. I think the only way we're accessing this endpoint is your delete survey button, so if that's not using POST then nothing should be. Similarly nothing should _actually_ be triggering the endpoint without a surveyId, that's also technically not a problem, although it would cause an error if it were to happen.

**Comment by Rayatk** [comment]
For the button to work, the form should have a POST method. The DELETE is handled by AJAX in the js. The controller also needs to handle POST requests as it is not directly interacting with the js.

**Comment by Rayatk** [comment]
The button worked however it showed Forbidden error after clicking. This is due to missing CSRF tokens which means changing the security configuration. Issue closed due to complexity.

**Pull request closed without merging**
